<?php
session_start();
require "vendor/autoload.php";

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $message = "";
    $email = $_POST["email"];
    $password = $_POST["password"];
    if (empty($email) || empty($password)) {
        $message = "Please fill in all fields.";
        echo $message;
        // header("Location: register.php");
        die();
    } elseif (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        $message = "Invalid email format.";
        echo $message;
        // header("Location: register.php");
        die();
    } else {
        $service = new PHPSupabase\Service(
            "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzZXBqZ3h4b3pleWt0amtiZXdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzYwMzgwODQsImV4cCI6MTk5MTYxNDA4NH0.zusO9r5QquROh2XfQ6CIM0sbL3Re2KPtSOsHK7lsPfc",
            "https://hsepjgxxozeyktjkbewc.supabase.co/auth/v1/"
        );

        $auth = $service->createAuth();

        try {
            $auth->signInWithEmailAndPassword($email, $password);
            $data = $auth->data(); // get the returned data generated by request

            if (isset($data->access_token)) {
                $userData = $data->user; //get the user data
                echo 'Login successfully for user ' . $userData->email;
                // header("Location: register.php");

                //save the $data->access_token in Session, Cookie or other for future requests.
            }
        } catch (Exception $e) {
            echo $auth->getError();
        }
    }
}
?>